version: '3'

services:
  backend:
    image: api
    restart: always
    build: ./api
    ports:
      - 5000:5000
    networks:
      - backend
      - frontend
  client:
    image: front
    restart: always
    build: .
    environment:
      NODE_ENV: production
    links:
      - backend
    ports:
      - "3000:3000"
    networks: 
      - frontend  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge